EventCalendar/urls.py
from django.urls import path, include

from . import views

app_name = 'EventCalendar'
urlpatterns = [
    path('', views.IndexUsingCulling, name='events'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('event_tag=<str:tag_name>/', views.tag_filtered, name='events_tag_filtered'),
    path('event/<int:event_id>/sendcomment', views.send_comment, name='send_comment'),
]



#you can also do like that: event/<int:event_id>/<int:some_param>/ to intercept multiple parameters
#in here: event_id and some_param are the names of the variables and as such they should be
#initiated in params of view with the very same names

StartupStudio/urls.py
import markdownx
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('news/', include('NewsFeed.urls')),
    path('event_news/', include('EventCalendar.urls')),
    path('', RedirectView.as_view(url='/news/', permanent=True)),
    path('c/', include('core.urls')),
    path('MyProfile/', include('MyProfile.urls')),
]

urlpatterns += [
    path('markdownx/', include('markdownx.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #Удалить после разработки

core/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = 'core'
urlpatterns = [
    #path('', views.index, name='index'),
    path('register', views.register_request, name='register'),
    path('login', RedirectView.as_view(url=reverse_lazy('accounts/login/')), name='login_core'),
    path('logout', views.logout_view, name='logout'),
    path('projects/<int:pk>/', views.project_detail_view, name='project_detail'),
]

#team urls
urlpatterns += [
    path('projects/<int:pk>/teams', views.look_project_teams, name='project_teams'),
    path('projects/team/<int:team_pk>', views.team_detailed_view, name='team_detailed'),
    # basically a template for a team's page
    path('projects/<int:project_pk>/teams/create', views.create_team_view, name='project_teams_create'),
    # TODO: WIP And bottom too
    path('projects/teams/join', views.join_team_view, name='join_team'),
    path('projects/team/<int:team_pk>/applications', views.look_project_team_applicants,
         name='project_teams_applications'),
    path('projects/team/<int:team_pk>/applications/<int:entry_pk>/<str:new_status>',
         views.team_change_status_event_entry_view, name='team_accept_or_deny_applicant'),
]

#project urls
urlpatterns += [
    path('projects/<int:project_pk>/send_notice', views.send_notice, name='project_send_notice'),
    path('projects/<int:project_pk>/send_message/<str:team_pk>', views.send_message, name='project_send_message'),
    path('projects/<int:project_pk>/get_messages_ajax/<str:channel_pk>', views.AjaxGetMessages.as_view(),
         name='ajax_get_messages'),
    path('projects/<int:pk>/applicants', views.look_project_applicants_view, name='check_applicants_for_project'),
    path('projects/<int:project_pk>/applicants/<int:entry_pk>/<str:new_status>', views.change_status_event_entry_view,
         name='accept_or_deny_applicant'),
    path('projects/<int:pk>/participants', views.look_project_participants_view, name='look_participants_of_project'),
    # path('e/<int:pk>/', views.ProjectDetailedView.as_view(), name='project_detail'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    ##TODO: RENAME ALL EVENTS TO PROJECTS IN THIS MODULE
    path('projects/my_projects', views.my_projects_view, name='my_projects_list'),
    path('projects/<int:pk>/enter', views.enter_the_project_view, name='enter_the_project_view'),
    # path('projects/create/', views.ProjectCreate.as_view(), name='project_create'),
    path('projects/create/', views.create_project_view, name='project_create'),
    path('projects/pending', views.accept_new_projects_view, name='new_pending_projects_mod'),
    path('projects/pending/<int:pk>/accept', views.accept_project_view, name='accept_project_mod'),
    path('projects/pending/<int:pk>/deny', views.deny_project_view, name='deny_project_mod'),
    path('projects/<int:pk>/update', views.ProjectUpdate.as_view(), name='project_update'),
    path('projects/<int:pk>/delete', views.ProjectDelete.as_view(), name='project_delete'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('load_skills/', views.load_skills, name='load_skills'),
]

urlpatterns+=[
    #path('myprofile/', views.my_profile, name='my_profile'), #eto zaglushka
    path('myprofile/change', views.my_profile_change_view, name='my_profile_change'),
    path('projects/<int:pk>/finish', views.finish_project_view, name='finish_project'),
]

EventCalendar/models.py
import datetime

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

from UserSystem.models import CustomUser


class EventTag(models.Model):
    tag_name = models.CharField(max_length=40)

    def __str__(self):
        return self.tag_name


class EventPage(models.Model):
    event_title = models.CharField(max_length=200)
    pub_date = models.DateField('date published')
    start_date = models.DateTimeField('start date')
    ending_date = models.DateTimeField('ending date')
    entry_deadline = models.DateTimeField('entry deadline')
    event_organiser = models.CharField(max_length=60)
    event_text = MarkdownxField()
    event_image = models.CharField('link to the picture used in the post', max_length=400, null=True, blank=True)
    event_tags = models.ManyToManyField(EventTag) #Tag Fields following Many to Many rules
    event_main_text_culling = models.IntegerField(  # providing minimal and max values for text Culling
        default=800,
        validators=[
            MaxValueValidator(800),
            MinValueValidator(1)
        ]
    )
    author = models.ForeignKey(CustomUser, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ["-start_date"]

    def __str__(self):
        return self.event_title

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=4) <= self.pub_date <= now

    def formatted_markdown(self):
        return markdownify(self.event_text)


class EventComment(models.Model):
    article = models.ForeignKey(EventPage, on_delete=models.CASCADE)
#    user_name = models.CharField(max_length=30)
    user_id = models.ForeignKey(CustomUser,  null=True, on_delete=models.SET_NULL)
    comment_text = models.CharField(max_length=600)
    pub_datetime = models.DateTimeField('date published')

    class Meta:
        ordering = ["pub_datetime"]

    def __str__(self):
        return self.user_id.username + ": " + str(self.comment_text)[:20] + " at " + str(self.pub_datetime.strftime("%Y-%m-%d %H:%M:%S"))


# Create your models here.

EventCalendar/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from EventCalendar.models import EventPage, EventComment
from UserSystem.models import CustomUser


def IndexUsingCulling(request):
    latest_event_list = EventPage.objects.filter(pub_date__lte=timezone.now())[:10]
    for item in latest_event_list:
        item.event_text = item.event_text[:item.event_main_text_culling]
    context = {'latest_event_list': latest_event_list}
    return render(request, 'EventCalendar/index.html', context)
    #paginate_by = 10 - pagination
    #events/?page=2 go to page 2 using GET paramethers
    #TODO: Events paginations through ListView pagination


class DetailView(generic.DetailView):
    model = EventPage
    template_name = 'EventCalendar/detail.html'

    def get_queryset(self):
        """
        Excludes any articles that aren't published yet.
        """
        return EventPage.objects.filter(pub_date__lte=timezone.now())


@login_required
def tag_filtered(request, tag_name):
    latest_event_list = EventPage.objects.filter(event_tags__tag_name=tag_name).filter(pub_date__lte=timezone.now())[:10]
    for item in latest_event_list:
        item.event_text = item.event_text[:item.event_main_text_culling]
    context = {'latest_event_list': latest_event_list}
    context['tag'] = tag_name
    return render(request, 'EventCalendar/index.html', context)
# Create your views here.


#TODO: MEDIUM PRIO: Проверить, все ли view написаны корректно, и можно ли заменить некоторые на обобщенные
def send_comment(request, event_id):
    if request.user.is_authenticated:
        event = get_object_or_404(EventPage, pk=event_id)
        q = EventComment(article=event, user_id=request.user, pub_datetime=timezone.now(), comment_text=request.POST['comment_text'])
        q.save()
    return HttpResponseRedirect(reverse('EventCalendar:detail', args=(event_id,)))

EventCalendar/templates/EventCalendar/detail.html
{% extends "base.html" %}
{% block title %}
<title>Мероприятия</title>
{% endblock %}
{% block content %}
<article>
    <h2><a href="{% url 'EventCalendar:detail' eventpage.id %}">{{ eventpage.event_title }}</a></h2>
        <div class="articleMainBody" style="display: flex; justify-content: space-between;">
            <div class="article_text">
                <p> Конец приема заявок: {{ eventpage.entry_deadline }} </p>
                <p> Начало: {{ eventpage.start_date }} </p>
                <p> Конец: {{ eventpage.ending_date }} </p>
            <p> Организатор: {{ eventpage.event_organiser  }}</p>
            <p> {{eventpage.event_text}} </p>
            <p> Призовой фонд: {{ eventpage.event_prize }}</p>
            </div>
            <div class="article_image">
            <img src="{{ eventpage.event_image }}" style="max-height: 256px; max-width: 400px; padding-left: 50px;">
            </div>
        </div>
        {% for tag in eventpage.event_tags.all %}
            <p class="tag" style="display:inline;"><a href="{% url 'EventCalendar:events_tag_filtered' tag.tag_name %}">{{ tag.tag_name }}</a></p>
        {% endfor %}
    <p>Опубликовано: {{ eventpage.pub_date }}</p>
    <div class="commentBlock">
        Комментарии:
        {% for comment in eventpage.eventcomment_set.all %}
            <div class="box">
						<div class="Name">{{comment.user_id.username}} {{comment.pub_time}}
                        <p>{{comment.comment_text}}</p>
                        </div>
			</div>
        {% endfor %}
        {% if user.is_authenticated %}
        <div id="messagewindow">
				<form name = "f2" action="{% url 'EventCalendar:send_comment' eventpage.pk  %}" method="post">
				{% csrf_token %}
                    <div id="sendcontainer"><textarea  name="comment_text" cols="40" rows="5" placeholder="Write your comment here..." id="chatbox"> </textarea>
					<div id="buttoncontainer">
						<input type="submit" name="button" value="Отправить" id="sendbutton">
					</div>
                    <textarea style="display: none;" name="user_id">1</textarea>
				</div>
				</form>
        </div>
        {% else %}
        <p align="center" class="login_to_comment_warning">Войдите, чтобы оставить комментарий</p>
        {% endif %}
    </div>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
</article>
{% endblock %}

EventCalendar/templates/EventCalendar/index.html
{% extends "base.html" %}
{% block title %}
<title>Мероприятия</title>
{% endblock %}
{% block content %}
    {% if tag %}
        <p align="center"><a href="{% url 'EventCalendar:events' %}">Сбросить фильтры</a></p>
    {% endif %}
{% if latest_event_list %}
    {% for event_article in latest_event_list %}
        <article>
            <h2><a href="{% url 'EventCalendar:detail' event_article.id %}">{{ event_article.event_title }}</a></h2>
        <div class="articleMainBody" style="display: flex; justify-content: space-between;">
            <div class="article_text event_container">
                <p> Конец приема заявок: {{ event_article.entry_deadline }} </p>
                <p> Начало: {{ event_article.start_date }} </p>
                <p> Конец: {{ event_article.ending_date }} </p>
            <p> Организатор: {{ event_article.event_organiser  }}</p>
            <p> {{event_article.formatted_markdown | safe}} </p>
            </div>
            <div class="article_image">
            <img src="{{ event_article.event_image }}" style="max-height: 256px; max-width: 400px; padding-left: 50px;">
            </div>
        </div>
        {% for tag in event_article.event_tags.all %}
            <p class="tag" style="display:inline;"><a href="{% url 'EventCalendar:events_tag_filtered' tag.tag_name %}">{{ tag.tag_name }}</a></p>
        {% endfor %}
        </article>
    {% endfor %}
{% else %}
    <p>No news are available.</p>
{% endif %}
{% endblock %}