EventCalendar/urls.py
from django.urls import path, include

from . import views

app_name = 'EventCalendar'
urlpatterns = [
    path('', views.IndexUsingCulling, name='events'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('event_tag=<str:tag_name>/', views.tag_filtered, name='events_tag_filtered'),
    path('event/<int:event_id>/sendcomment', views.send_comment, name='send_comment'),
]



#you can also do like that: event/<int:event_id>/<int:some_param>/ to intercept multiple parameters
#in here: event_id and some_param are the names of the variables and as such they should be
#initiated in params of view with the very same names

MyProfile/urls.py
import markdownx
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = 'MyProfile'
urlpatterns = [
    path('', views.get_profile, name='get_profile'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
]

NewsFeed/urls.py
from django.urls import path, include
from . import views

app_name = 'NewsFeed'
urlpatterns = [
    path('', views.index_using_culling, name='news'),
    path('<int:page_num>/', views.index_using_culling, name='news_on_page'), #open desired page
    path('article/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('tag=<str:tag_name>/', views.tag_filtered, name='news_tag_filtered'),
    path('tag=<str:tag_name>/<int:page_num>/', views.tag_filtered, name='news_tag_filtered_with_page_num'),
    path('article/<int:article_id>/sendcomment', views.send_comment, name='send_comment'),
    path('article/create', views.create_article_view, name='create_article'),
]

urlpatterns += [
    path('markdownx/', include('markdownx.urls')),
]
#put create news here btw
    #Maybe i should make tags as parameters for get view

StartupStudio/urls.py
import markdownx
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('news/', include('NewsFeed.urls')),
    path('event_news/', include('EventCalendar.urls')),
    path('', RedirectView.as_view(url='/news/', permanent=True)),
    path('c/', include('core.urls')),
    path('MyProfile/', include('MyProfile.urls')),
]

urlpatterns += [
    path('markdownx/', include('markdownx.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #Удалить после разработки

core/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = 'core'
urlpatterns = [
    #path('', views.index, name='index'),
    path('register', views.register_request, name='register'),
    path('login', RedirectView.as_view(url=reverse_lazy('accounts/login/')), name='login_core'),
    path('logout', views.logout_view, name='logout'),
    path('projects/<int:pk>/', views.project_detail_view, name='project_detail'),
]

#team urls
urlpatterns += [
    path('projects/<int:pk>/teams', views.look_project_teams, name='project_teams'),
    path('projects/team/<int:team_pk>', views.team_detailed_view, name='team_detailed'),
    # basically a template for a team's page
    path('projects/<int:project_pk>/teams/create', views.create_team_view, name='project_teams_create'),
    # TODO: WIP And bottom too
    path('projects/teams/join', views.join_team_view, name='join_team'),
    path('projects/team/<int:team_pk>/applications', views.look_project_team_applicants,
         name='project_teams_applications'),
    path('projects/team/<int:team_pk>/applications/<int:entry_pk>/<str:new_status>',
         views.team_change_status_event_entry_view, name='team_accept_or_deny_applicant'),
]

#project urls
urlpatterns += [
    path('projects/<int:project_pk>/send_notice', views.send_notice, name='project_send_notice'),
    path('projects/<int:project_pk>/send_message/<str:team_pk>', views.send_message, name='project_send_message'),
    path('projects/<int:project_pk>/get_messages_ajax/<str:channel_pk>', views.AjaxGetMessages.as_view(),
         name='ajax_get_messages'),
    path('projects/<int:pk>/applicants', views.look_project_applicants_view, name='check_applicants_for_project'),
    path('projects/<int:project_pk>/applicants/<int:entry_pk>/<str:new_status>', views.change_status_event_entry_view,
         name='accept_or_deny_applicant'),
    path('projects/<int:pk>/participants', views.look_project_participants_view, name='look_participants_of_project'),
    # path('e/<int:pk>/', views.ProjectDetailedView.as_view(), name='project_detail'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    ##TODO: RENAME ALL EVENTS TO PROJECTS IN THIS MODULE
    path('projects/my_projects', views.my_projects_view, name='my_projects_list'),
    path('projects/<int:pk>/enter', views.enter_the_project_view, name='enter_the_project_view'),
    # path('projects/create/', views.ProjectCreate.as_view(), name='project_create'),
    path('projects/create/', views.create_project_view, name='project_create'),
    path('projects/pending', views.accept_new_projects_view, name='new_pending_projects_mod'),
    path('projects/pending/<int:pk>/accept', views.accept_project_view, name='accept_project_mod'),
    path('projects/pending/<int:pk>/deny', views.deny_project_view, name='deny_project_mod'),
    path('projects/<int:pk>/update', views.ProjectUpdate.as_view(), name='project_update'),
    path('projects/<int:pk>/delete', views.ProjectDelete.as_view(), name='project_delete'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('load_skills/', views.load_skills, name='load_skills'),
]

urlpatterns+=[
    #path('myprofile/', views.my_profile, name='my_profile'), #eto zaglushka
    path('myprofile/change', views.my_profile_change_view, name='my_profile_change'),
    path('projects/<int:pk>/finish', views.finish_project_view, name='finish_project'),
]

StartupStudio/templates/base.html
<!doctype html>
<html>
{% block header %}
<head>
 {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'NewsFeed/style.css' %}">
<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">-->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block title %}
        <title>Base</title>
    {% endblock %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>
{% endblock %}
<body>
    <main>
    {% block navigation %}
        <nav>
		<a href="{% url 'NewsFeed:news' %}">Новости</a>
		<a href="{% url 'EventCalendar:events' %}">Мероприятия</a>
		<a href="{% url 'core:project_list' %} ">Проекты</a>
		<a href="{% url 'core:my_projects_list' %}">Мои проекты</a>
		<a href="{% url 'MyProfile:get_profile' %}">Мой профиль</a>
	    </nav>
    {% endblock %}
    {% block user %}
        <p align="center"> {% if user.is_authenticated %} Текущий пользователь: {{ request.user }} <a href="{% url 'logout' %}?next={{request.path}}">Выйти</a>
        {% else %} Вы не вошли в аккаунт:  <a href="{% url 'login' %}?next={{request.path}}">Войти</a> {% endif %}</p>
    {% endblock %}
    {% block content %}

    {% endblock %}
    </main>
</body>
</html>