MyProfile/urls.py
import markdownx
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = 'MyProfile'
urlpatterns = [
    path('', views.get_profile, name='get_profile'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
]

StartupStudio/urls.py
import markdownx
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('news/', include('NewsFeed.urls')),
    path('event_news/', include('EventCalendar.urls')),
    path('', RedirectView.as_view(url='/news/', permanent=True)),
    path('c/', include('core.urls')),
    path('MyProfile/', include('MyProfile.urls')),
]

urlpatterns += [
    path('markdownx/', include('markdownx.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #Удалить после разработки

core/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = 'core'
urlpatterns = [
    #path('', views.index, name='index'),
    path('register', views.register_request, name='register'),
    path('login', RedirectView.as_view(url=reverse_lazy('accounts/login/')), name='login_core'),
    path('logout', views.logout_view, name='logout'),
    path('projects/<int:pk>/', views.project_detail_view, name='project_detail'),
]

#team urls
urlpatterns += [
    path('projects/<int:pk>/teams', views.look_project_teams, name='project_teams'),
    path('projects/team/<int:team_pk>', views.team_detailed_view, name='team_detailed'),
    # basically a template for a team's page
    path('projects/<int:project_pk>/teams/create', views.create_team_view, name='project_teams_create'),
    # TODO: WIP And bottom too
    path('projects/teams/join', views.join_team_view, name='join_team'),
    path('projects/team/<int:team_pk>/applications', views.look_project_team_applicants,
         name='project_teams_applications'),
    path('projects/team/<int:team_pk>/applications/<int:entry_pk>/<str:new_status>',
         views.team_change_status_event_entry_view, name='team_accept_or_deny_applicant'),
]

#project urls
urlpatterns += [
    path('projects/<int:project_pk>/send_notice', views.send_notice, name='project_send_notice'),
    path('projects/<int:project_pk>/send_message/<str:team_pk>', views.send_message, name='project_send_message'),
    path('projects/<int:project_pk>/get_messages_ajax/<str:channel_pk>', views.AjaxGetMessages.as_view(),
         name='ajax_get_messages'),
    path('projects/<int:pk>/applicants', views.look_project_applicants_view, name='check_applicants_for_project'),
    path('projects/<int:project_pk>/applicants/<int:entry_pk>/<str:new_status>', views.change_status_event_entry_view,
         name='accept_or_deny_applicant'),
    path('projects/<int:pk>/participants', views.look_project_participants_view, name='look_participants_of_project'),
    # path('e/<int:pk>/', views.ProjectDetailedView.as_view(), name='project_detail'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    ##TODO: RENAME ALL EVENTS TO PROJECTS IN THIS MODULE
    path('projects/my_projects', views.my_projects_view, name='my_projects_list'),
    path('projects/<int:pk>/enter', views.enter_the_project_view, name='enter_the_project_view'),
    # path('projects/create/', views.ProjectCreate.as_view(), name='project_create'),
    path('projects/create/', views.create_project_view, name='project_create'),
    path('projects/pending', views.accept_new_projects_view, name='new_pending_projects_mod'),
    path('projects/pending/<int:pk>/accept', views.accept_project_view, name='accept_project_mod'),
    path('projects/pending/<int:pk>/deny', views.deny_project_view, name='deny_project_mod'),
    path('projects/<int:pk>/update', views.ProjectUpdate.as_view(), name='project_update'),
    path('projects/<int:pk>/delete', views.ProjectDelete.as_view(), name='project_delete'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('load_skills/', views.load_skills, name='load_skills'),
]

urlpatterns+=[
    #path('myprofile/', views.my_profile, name='my_profile'), #eto zaglushka
    path('myprofile/change', views.my_profile_change_view, name='my_profile_change'),
    path('projects/<int:pk>/finish', views.finish_project_view, name='finish_project'),
]

MyProfile/models.py
from django.db import models
from datetime import date
from UserSystem.models import CustomUser
# class Status(models.Model):
#     name_status = models.CharField(max_length=30, verbose_name="Status Name")
#
#     def __str__(self):
#         return self.name_status


class Profile(models.Model):
    # Common Fields
    STATUS_CHOICES = [
        ('student', 'Студент'),
        ('teacher', 'Преподаватель'),
        ('company', 'Компания'),
    ]

    photo = models.ImageField(upload_to='images/', blank=True)
    lastname = models.CharField(max_length = 30, help_text = "Введите фамилию", verbose_name="Last Name")
    firstname = models.CharField(max_length = 30, help_text = "Введите имя", verbose_name="First Name")
    sername = models.CharField(max_length = 30, help_text = "Введите отчество", verbose_name="Sername")
    birth_date = models.DateField(default=date.today, help_text = "Введите дату рождения", verbose_name="Birth date")
    skills = models.CharField(max_length=500, help_text="Заполните резюме", verbose_name="Skills")
    email = models.EmailField(max_length=254, help_text="Введите электронную почту", verbose_name="Email") # нужно подтягивать с регистрации
    contact_info = models.CharField(max_length=18, help_text="Введите номер телефона", verbose_name="Contact Information")
    links = models.CharField(max_length=300, help_text="Ссылки на социальные сети, для связи", blank=True, null=True, verbose_name="Links")
    extrainfo = models.CharField(max_length=300, help_text="Дополнительная информация", blank = True, null = True, verbose_name="Extra Information")

    # status_id = models.ForeignKey(Status, on_delete=models.CASCADE)
    status_id=models.CharField(max_length = 30, help_text = "Введите статус", verbose_name="Status Name", choices=STATUS_CHOICES)

    # Status Fields
    # for student
    direction = models.CharField(max_length=100, help_text="Введите направление обучения", verbose_name="Direction")
    graduate_date = models.DateField(default=date.today, help_text = "Введите дату поступления", verbose_name="Graduate Date")
    # for teacher and company
    company_title = models.CharField(max_length=100, help_text="Введите название компании", verbose_name="Company Title")
    company_info = models.CharField(max_length=300, help_text="Информация о компании", blank = True, null = True, verbose_name="Company Information")
    company_links = models.CharField(max_length=500, help_text="Укажите сайт компании", verbose_name="Company Information")
    job_title = models.CharField(max_length=100, help_text="Укажите свою должность", verbose_name="Job Title")
    department = models.CharField(max_length=30, help_text="Укажите свою кафедру", verbose_name="Department")
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE,blank = True, null = True ,verbose_name="User")
    def __str__(self):
        return self.user.email
    def __repr__(self)->str:
        return self.user.email

core/models.py
from django.urls import reverse
from django.utils import timezone

from django.db import models

from UserSystem.models import CustomUser


class Direction(models.Model):
    direction_name = models.CharField(max_length=100)
    direction_info = models.CharField(max_length=800, blank=True)

    def __str__(self):
        return self.direction_name


class EventType(models.Model):
    event_type_name = models.CharField(max_length=50, unique=True)
    event_type_info = models.CharField(max_length=800, blank=True)

    def __str__(self):
        return self.event_type_name


class Skill(models.Model):
    skill_name = models.CharField(max_length=80, unique=True)
    skill_info = models.CharField(max_length=800, blank=True)
    direction = models.ForeignKey(Direction, on_delete=models.CASCADE, null=True,default=None)
    def __str__(self):
        return self.skill_name



#Deprecated?
class EntryStatus(models.Model):
    entry_name = models.CharField(max_length=80)

    def __str__(self):
        return self.entry_name


class Team(models.Model):
    team_name = models.CharField(max_length=80)
    team_members = models.ManyToManyField(CustomUser, related_name="team_members")
    team_captain = models.ForeignKey(CustomUser, null=True, on_delete=models.SET_NULL, related_name="team_captain")
    team_info = models.CharField(max_length=800, null=True, blank=True)
    team_lfg_message = models.CharField(max_length=800, null=True, blank=True)
    is_looking_for_group = models.BooleanField(default=False)

    def __str__(self):
        return self.team_name


class Project(models.Model):
    project_name = models.CharField(max_length=150)
    project_info = models.CharField(max_length=1500)
    event_type = models.ForeignKey(EventType, null=True, on_delete=models.SET_NULL)
    direction_type = models.ForeignKey(Direction, null=True, on_delete=models.SET_NULL)
    project_skills = models.ManyToManyField(Skill)

    project_authors = models.ManyToManyField(CustomUser, related_name="project_authors")
    project_participants = models.ManyToManyField(CustomUser, blank=True, null=True, related_name="project_participants")
    project_teams = models.ManyToManyField(Team, blank=True)
    maximum_members_in_team = models.IntegerField(default=4)

    pub_date = models.DateTimeField('Date Time published', default=timezone.now())
    project_start = models.DateTimeField('Project Start')
    project_end = models.DateTimeField('Project Ending')

    # project status should be mad of lists

    PROJECT_STATUS = (
        ('pen', 'На рассмотрении'), ('acc', 'Принято'), ('den', 'Отклонено'), ('act', 'Активно'), ('fin', 'Завершено'))

    project_status = models.CharField(max_length=3, choices=PROJECT_STATUS, blank=True, default='pen',
                                      help_text="Current project status")

    def __str__(self):
        return self.project_name

    def get_absolute_url(self):
        return reverse('core:project_detail', args=[int(self.id)])

    class Meta:
        permissions = [
            ("can_manage_projects", "Can manage projects"),
            ("can_moderate_projects", "Can moderate incoming projects"),
            ("can_create_projects", "Can create projects"),
            ("can_enter_projects", "Can enter projects"),
            ("can_view_project_details", "Can view project details"),
        ]
        ordering = ['project_start'] #take a notice, that this operation could be costly,
    #consider swapping it to order_by on related controllers
    #ordering is being called every query is called, that also includes foreignkeys and many-to-many fields


class ProjectEntry(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('Время, когда заяка была отправлена', default=timezone.now()) #use timezone.now() to apply default state to the date field
    status_changed_date = models.DateTimeField('Время, когда статус заявки был изменен', default=timezone.now())

    ENTRY_STATUS = (('pen', 'На рассмотрении'), ('acc', 'Заявка одобрена'), ('den', 'Заявка отклонена'))
    status = models.CharField(max_length=3, choices=ENTRY_STATUS, blank=True, default='pen',
                              help_text="Current entry status")

    def __str__(self):
        return self.project.project_name

    #this type of ordering uses too many resources, so probably it's better to move it to the other place
    #class Meta:
    #    ordering = ['-status']


class ProjectResult(models.Model):
    project = models.ForeignKey(Project, null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(CustomUser, null=True, on_delete=models.SET_NULL)
    project_result = models.CharField(max_length=150)
    users_team = models.CharField(max_length=80)

    def __str__(self):
        return self.project_result


class ProjectChatMessage(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, null=True, on_delete=models.SET_NULL)
    message_text = models.CharField(max_length=800) #FOR FUTURE: Calling fields like this: MODEL_TEXT proved kinda inconvinient
    pub_datetime = models.DateTimeField('Date published')   #might as well do just "text" next time, so models are easier to swap between

    def __str__(self):
        return self.message_text


class TeamChatMessage(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, null=True, on_delete=models.SET_NULL)
    message_text = models.CharField(max_length=800)
    pub_datetime = models.DateTimeField('Date published')

    def __str__(self):
        return self.message_text


class TeamEntry(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    ENTRY_STATUS = (('pen', 'Рассматривается'), ('acc', 'Принято'), ('den', 'Отклонено'))
    status = models.CharField(max_length=3, choices=ENTRY_STATUS, blank=True, default='pen',
                              help_text="Current entry status")

    def __str__(self):
        return self.user.username + " to " + self.team.team_name

# Create your models here.


class ProjectNotice(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    notice_text = models.CharField(max_length=800)
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, blank=True, null=True)
    pub_datetime = models.DateTimeField(default=timezone.now())

MyProfile/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib import messages

from .models import Profile
from UserSystem.models import CustomUser
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from core.models import Project

from .forms import ProfileForm


@login_required
def create_profile(request):
    if Profile.objects.filter(user_id=request.user.id).exists():
        return redirect('MyProfile:get_profile')
    if request.method == "POST":
        form = ProfileForm(request.POST)
        print('Working')
        if form.is_valid():
            profile = form.save()
            profile.user_id=request.user.id
            profile.save()
            return redirect('MyProfile:get_profile')
        else:
            # Получаем ошибки валидации
            errors = form.errors
            # Обрабатываем ошибки по необходимости
            for field, error in errors.items():
                print(f"Ошибка в поле {field}: {error}")
    else:
        form = ProfileForm()


    return render(request, 'MyProfile/create_profile.html',{'form': form})


@login_required
def get_profile(request):
    try:
        user_profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        return redirect('MyProfile:create_profile')
    projects = Project.objects.filter(Q(project_authors=request.user.id) | Q(project_participants=request.user.id))

    ctx = {'first_name': user_profile.firstname,
           'last_name': user_profile.lastname,
           'sername': user_profile.sername,
           'birth_date': user_profile.birth_date,
           'email': user_profile.user.email,
           'skills': user_profile.skills,
           'extrainfo': user_profile.extrainfo,
           'contact_info': user_profile.contact_info,
           'direction': user_profile.direction,
           'graduate_date': user_profile.graduate_date,
           'status_id': str(user_profile.status_id),
           'photo': user_profile.photo,
           'job_title': user_profile.job_title,
           'department': user_profile.department,
           'company_title': user_profile.company_title,
           'company_info': user_profile.company_info,
           'company_links': user_profile.company_links,
           'links': user_profile.links,
           'contact_info': user_profile.contact_info,
           'project_list': projects
           }
    print(ctx)
    if user_profile is None:
        raise PermissionDenied()
    return render(request, 'MyProfile/main_profile.html', context=ctx)


@login_required
def delete_profile(request):
    user_profile = Profile.objects.get(user=request.user)
    user_profile.delete()
    return redirect('/news')


@login_required
def update_profile(request):
    profile  = Profile.objects.get(user=request.user)
    print(profile.birth_date)
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('MyProfile:get_profile')
    else:
        form = ProfileForm(instance=profile)

    return render(request, 'MyProfile/update_profile.html', {'form': form})

core/templates/core/loggedout.html
{% extends "base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
    <h1>Logged out</h1>
    <p>You have been successfully logged out. You can <a href="{% url "login" %}">log-in again</a>.</p>
{% endblock %}

core/templates/core/project_detail.html
{% extends "base.html" %}
{% block title %}
    <title>Новости</title>
{% endblock %}
{% block content %}
    <article>
        <div class="main-container">
            <div class="main-info-container">
                <h2>{{ project.project_name }}</h2>
                <h3>Тип мероприятия: {{ project.event_type }} </h3>
                <div>{{ project.project_info }}</div>
                <div>Направление: {{ project.direction_type }}</div>
                <div>Навыки для участия:</div>
                <div class="tag_container"> {% for skill in project.project_skills.all %}
                    <div class="tag">{{ skill.skill_name }}</div>
                {% endfor %}</div>
                <div>Авторы: {% for author in project.project_authors.all %}
                    <div>{{ author.username }}</div> {% endfor %}
                </div>
                <div>Начало: {{ project.project_start }}</div>
                <div>Конец: {{ project.project_end }}</div>
                <div>Статус проекта: {{ project.get_project_status_display }}</div>
                {% if is_author %}
                    <div><a class="to_link" href="{% url 'core:check_applicants_for_project' project.id %}"> Перейти к
                        заявкам проекта </a></div>
                    <div><a class="to_link" href="{% url 'core:look_participants_of_project' project.id %}">Показать
                        участников проекта</a></div>

                {% else %}
                    {% if already_entered %} {# although you can easily swap already_entered for {{ project_entry }} #}
                        {% if project_entry.status == 'pen' %}
                            {# you can leave it be, as it won't necessary be much better #}
                            <div>Статус заявки: <span
                                    class="entry_status">Вы подали заявку на вступление на этот проект</span></div>
                        {% elif project_entry.status == 'acc' %}
                            <div>Статус заявки: <span class="entry_status">Заявка одобрена</span></div>
                            <div class="regular_text">Ваша команда: {% if team %} <a href="{% url 'core:team_detailed' team.id %}?project_link={% url 'core:project_detail' project.id %}">{{ team.team_name }}</a> {% else %} У вас пока нет команды <a href="{% url 'core:project_teams' project.id %}">Найти</a> {% endif %}</div>
                        {% elif project_entry.status == 'den' %}
                            <div>Статус заявки: <span class="entry_status">Заявка отклонена</span></div>
                        {% endif %}
                    {% elif user.is_authenticated %}
                        <div><a href="{% url 'core:enter_the_project_view' project.id %}"> Подать заявку на участие </a>
                        </div>
                    {% else %}
                        <div> Чтобы подать заявку, <a class="to_link" href="{% url 'login' %}"> Войдите </a></div>
                    {% endif %}
                {% endif %}
                <p>Опубликовано: {{ project.pub_date }}</p>
                <div class="shadebox"> Определить результаты проекта </div>
            </div>
            <div class="notice_board_outer">
                Объявления:
                <div class="notice_board">
                    {% if user.is_authenticated %}
                        <div class="message-container">
                            {% for notice in project.projectnotice_set.all %}
                                <div class="box">
                                    <div class="Name">{{ notice.user.username }} {{ notice.pub_datetime }}
                                        <p>{{ notice.notice_text }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        {% if is_author %}
                            <div id="messagewindow">
                                <form name="f2" action="{% url 'core:project_send_notice' project.id %}" method="post">
                                    {% csrf_token %}
                                    <div id="sendcontainer"><textarea name="notice_text" cols="50" rows="4"
                                                                      placeholder="Написать новое объявление..."
                                                                      id="send_notice_bos"> </textarea>
                                        <div id="buttoncontainer">
                                            <input type="submit" name="button" value="Отправить" id="sendbutton">
                                        </div>
                                        <textarea style="display: none;" name="user_id">1</textarea>
                                    </div>
                                </form>
                            </div>
                        {% else %}
                            <style> .message-container {
                                height: 100%
                            }</style>
                        {% endif %}
                    {% else %}
                        <p align="center" class="login_to_comment_warning">Войдите, чтобы оставить объявление</p>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if project_entry.status == 'acc' or is_author %}
            <div class="chat_outer_container">
            <div class="group_picker">
                <button id="general_chat_button" onclick="openChatGroup('general')">Общий чат</button>
                <button id="team_chat_button" onclick="openChatGroup('team')">Чат команды</button>
            </div>
            <div class="chat_wrap">
                <div class="chat_inner_container">
                    <div class="message_board">
                        <div id="general-messages" class="outer_chat_wrapper">
                            <div class="message-container" id="general-messages-container">
                                {% if general_messages %} {# TODO: swap this with ajax late #}
                                {% for message in general_messages %}
                                    <div class="box">
                                        <div class="Name">{{ message.user.username }} {{ message.pub_datetime }}
                                            <p>{{ message.message_text }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                                    {% else %}
                                    <div>Тут пока нет сообщений</div>
                                    {% endif %}
                            </div>
                        </div>
                        <div id="team-messages" class="outer_chat_wrapper">
                            <div class="message-container" id="team-messages-container" >
                                {% for message in team.teamchatmessage_set.all %}
                                    <div class="box">
                                        <div class="Name">{{ message.user.username }} {{ message.pub_datetime }}
                                            <p>{{ message.message_text }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                </div>
                    <div id="messagewindow">
                        <form name="send_message_form" id="send_message_form" action="{% url 'core:project_send_message' project.id "general" %}" method="post">
                            {% csrf_token %}
                            <div id="sendcontainer"><textarea name="message_text" cols="50" rows="4"
                                                              placeholder="Написать новое объявление..."
                                                              id="chatbox"> </textarea>
                                <div id="buttoncontainer">

                                    <button onclick="sendMessageAjax()" type="button" id="send-message-button">Отправить</button>
                                </div>
                                <textarea style="display: none;" name="user_id">1</textarea>
                            </div>
                        </form>
                    </div>

            </div>
            <script>

                //there should be a way to better organise all of that
                {% if project_entry.status == 'acc' or is_author %}
                var chat_groups = {'general': document.getElementById("general-messages"), 'team': document.getElementById("team-messages")}
                var group_overflows = {'general': document.getElementById("general-messages-container"), 'team': document.getElementById("team-messages-container")} // dictionary containing message containers
                //var general_link = "{% url 'core:project_send_message' project.id "general" %}"
                var receive_links = {'general':"{% url 'core:ajax_get_messages' project.id "general" %}"}  //links used to receive messages
                var links = {'general': "{% url 'core:project_send_message' project.id "general" %}"}    //links used to send messages

                var active_chat = 'general'
                var current_url = links[active_chat] //current send url

                links['team'] = ""
                {% endif %}
                {% if team %}
                    var team_message_link = "{% url 'core:project_send_message' project.id team.id %}"
                    links['team'] = team_message_link
                    receive_links['team'] = "{% url 'core:ajax_get_messages' project.id team.id %}"
                {% endif %}

                {# You can further automate it using Django templates adding additional groups to the dictionary #}

                {# injecting javascripts if user have rights to receive a messages #}
                {% if project_entry.status == 'acc' or is_author %}
                    function getMessagesGeneral(chosen_channel){
                        var doScroll = (group_overflows[chosen_channel].scrollTop === (group_overflows[chosen_channel].scrollHeight - group_overflows[chosen_channel].offsetHeight))
                        console.log('Requesting JSON');
                        $.getJSON(receive_links[chosen_channel], function(rowz){
                          //console.log('JSON', rowz);
                          $(group_overflows[chosen_channel]).empty();
                          for (var i = 0; i < rowz.length; i++){
                              line = rowz[i]
                              $(group_overflows[chosen_channel]).append(
                                  ' <div class=box>' +
                                  '                                        <div class="Name">' + line[0] + " " + line[3] +
                                  '                                            <p>' + line[2] + '</p>\n' +
                                  '                                        </div>\n' +
                                  '                                    </div>')
                          }
                          if (doScroll){
                              group_overflows[chosen_channel].scrollTop = group_overflows[chosen_channel].scrollHeight;
                          }
                          //getMessagesGeneral() //DON'T EVER DO THAT
                          setTimeout(getMessagesGeneral, 2000, chosen_channel) //some optimisations can be done, for example, pulling only new messages
                        });
                    }

                    function sendMessageAjax() {
                        var CSRFtoken = $('input[name=csrfmiddlewaretoken]').val();
                        var textbox = document.getElementById("chatbox");
                        var data = textbox.value;
                        console.log("sending ajax message: "+data)
                        textbox.value = "";
                        $.post(current_url, {message_text: data, csrfmiddlewaretoken: CSRFtoken}, function(response){ /* success */ });
                    }

                {% endif %}
                    $(document).ready(function(){
                        $.ajaxSetup({cache: false});
                        {% if project_entry.status == 'acc' or is_author %}
                            getMessagesGeneral('general');
                        {% endif %}
                        {% if team %}
                            getMessagesGeneral('team');
                        {% endif %}
                    })

                function openChatGroup(group) {
                    console.log("buttonPressed" + group);
                    for (const [key, value] of Object.entries(chat_groups)) {
                        console.log(key, value);
                        value.style.display = "none";
                    }
                    chat_groups[group].style.display = "block";
                    //document.getElementById("send_message_form").action = links[group]
                    current_url = links[group]

                    group_overflows[group].scrollTop = group_overflows[group].scrollHeight;
                }
            </script>
        {% endif %}

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    </article>
{% endblock %}