NewsFeed/urls.py
from django.urls import path, include
from . import views

app_name = 'NewsFeed'
urlpatterns = [
    path('', views.index_using_culling, name='news'),
    path('<int:page_num>/', views.index_using_culling, name='news_on_page'), #open desired page
    path('article/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('tag=<str:tag_name>/', views.tag_filtered, name='news_tag_filtered'),
    path('tag=<str:tag_name>/<int:page_num>/', views.tag_filtered, name='news_tag_filtered_with_page_num'),
    path('article/<int:article_id>/sendcomment', views.send_comment, name='send_comment'),
    path('article/create', views.create_article_view, name='create_article'),
]

urlpatterns += [
    path('markdownx/', include('markdownx.urls')),
]
#put create news here btw
    #Maybe i should make tags as parameters for get view

StartupStudio/urls.py
import markdownx
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('news/', include('NewsFeed.urls')),
    path('event_news/', include('EventCalendar.urls')),
    path('', RedirectView.as_view(url='/news/', permanent=True)),
    path('c/', include('core.urls')),
    path('MyProfile/', include('MyProfile.urls')),
]

urlpatterns += [
    path('markdownx/', include('markdownx.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #Удалить после разработки

core/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = 'core'
urlpatterns = [
    #path('', views.index, name='index'),
    path('register', views.register_request, name='register'),
    path('login', RedirectView.as_view(url=reverse_lazy('accounts/login/')), name='login_core'),
    path('logout', views.logout_view, name='logout'),
    path('projects/<int:pk>/', views.project_detail_view, name='project_detail'),
]

#team urls
urlpatterns += [
    path('projects/<int:pk>/teams', views.look_project_teams, name='project_teams'),
    path('projects/team/<int:team_pk>', views.team_detailed_view, name='team_detailed'),
    # basically a template for a team's page
    path('projects/<int:project_pk>/teams/create', views.create_team_view, name='project_teams_create'),
    # TODO: WIP And bottom too
    path('projects/teams/join', views.join_team_view, name='join_team'),
    path('projects/team/<int:team_pk>/applications', views.look_project_team_applicants,
         name='project_teams_applications'),
    path('projects/team/<int:team_pk>/applications/<int:entry_pk>/<str:new_status>',
         views.team_change_status_event_entry_view, name='team_accept_or_deny_applicant'),
]

#project urls
urlpatterns += [
    path('projects/<int:project_pk>/send_notice', views.send_notice, name='project_send_notice'),
    path('projects/<int:project_pk>/send_message/<str:team_pk>', views.send_message, name='project_send_message'),
    path('projects/<int:project_pk>/get_messages_ajax/<str:channel_pk>', views.AjaxGetMessages.as_view(),
         name='ajax_get_messages'),
    path('projects/<int:pk>/applicants', views.look_project_applicants_view, name='check_applicants_for_project'),
    path('projects/<int:project_pk>/applicants/<int:entry_pk>/<str:new_status>', views.change_status_event_entry_view,
         name='accept_or_deny_applicant'),
    path('projects/<int:pk>/participants', views.look_project_participants_view, name='look_participants_of_project'),
    # path('e/<int:pk>/', views.ProjectDetailedView.as_view(), name='project_detail'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    ##TODO: RENAME ALL EVENTS TO PROJECTS IN THIS MODULE
    path('projects/my_projects', views.my_projects_view, name='my_projects_list'),
    path('projects/<int:pk>/enter', views.enter_the_project_view, name='enter_the_project_view'),
    # path('projects/create/', views.ProjectCreate.as_view(), name='project_create'),
    path('projects/create/', views.create_project_view, name='project_create'),
    path('projects/pending', views.accept_new_projects_view, name='new_pending_projects_mod'),
    path('projects/pending/<int:pk>/accept', views.accept_project_view, name='accept_project_mod'),
    path('projects/pending/<int:pk>/deny', views.deny_project_view, name='deny_project_mod'),
    path('projects/<int:pk>/update', views.ProjectUpdate.as_view(), name='project_update'),
    path('projects/<int:pk>/delete', views.ProjectDelete.as_view(), name='project_delete'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('load_skills/', views.load_skills, name='load_skills'),
]

urlpatterns+=[
    #path('myprofile/', views.my_profile, name='my_profile'), #eto zaglushka
    path('myprofile/change', views.my_profile_change_view, name='my_profile_change'),
    path('projects/<int:pk>/finish', views.finish_project_view, name='finish_project'),
]

NewsFeed/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

from UserSystem.models import CustomUser


import datetime


class Tag(models.Model):
    tag_name = models.CharField(max_length=20)

    def __str__(self):
        return self.tag_name


class NewsArticle(models.Model):
    news_title = models.CharField(max_length=200) #Rename news_title to article_title for better clarity
    pub_date = models.DateField('date published', default=timezone.now())
    news_text = MarkdownxField() #Rename news_text to article_text for better clarity
    tags = models.ManyToManyField(Tag) #Tag Fields following Many to Many rules
    news_main_text_culling = models.IntegerField(  # providing minimal and max values for text Culling
        default=800,
        validators=[
            MaxValueValidator(800),
            MinValueValidator(1)
        ]
    )
    author = models.ForeignKey(CustomUser, null=True, on_delete=models.SET_NULL)


    def get_absolute_url(self):
        return reverse('NewsFeed:detail', args=[int(self.id)])

    def formatted_markdown(self):
        return markdownify(self.news_text)

    def __str__(self):
        return self.news_title

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=4) <= self.pub_date <= now

    class Meta:
        permissions = [
            ("create_new_news", "Can create new news"),
            ("delete_their_news", "Can delete their own news"),
            ("delete_any_news", "Can delete any news"),
        ]
        ordering = ["-pub_date"]


class Comment(models.Model):
    article = models.ForeignKey(NewsArticle, on_delete=models.CASCADE)
#    user_name = models.CharField(max_length=30)
    user_id = models.ForeignKey(CustomUser,  null=True, on_delete=models.SET_NULL)
    comment_text = models.CharField(max_length=600)
    pub_datetime = models.DateTimeField('date published')

    class Meta:
        ordering = ["pub_datetime"]

    def __str__(self):
        return self.user_id.username + ": " +str(self.comment_text)[:20] + " at " + str(self.pub_datetime.strftime("%Y-%m-%d %H:%M:%S"))

    def get_absolute_url(self):
        return reverse('NewsFeed:detail', args=[int(self.article.id)])



#class NewsPreview(models.Model): #Probably is unneeded, but if someone likes the idea I can work on that
#    news_title = models.CharField(max_length=200)
#    news_text_preview = models.CharField(max_length=800) #Possible data duplication... is there any way to avoid it? #Maybe we should just mark the end of the preview in original text by invisible markdown
#    main_article_link = models.CharField(max_length=300) #Questionable decision, about to be hardcoded, weak to directory renames and such
#                                                         #Possible solution? swap it with a link to a model and make Django do the job of putting links in
#    pub_date = models.DateField('date published')  # Implementing preview culling is possible to prevent data duplication, while custom headers are still ?optional?
#
#    def __str__(self):
#        return self.news_title
#
#    def was_published_recently(self):
#        now = timezone.now()
#        return now - datetime.timedelta(days=4) <= self.pub_date <= now


# Create your models here.

NewsFeed/forms.py
from django.forms import ModelForm

from NewsFeed.models import NewsArticle


class CreateNewsForm(ModelForm):
    class Meta:
        model = NewsArticle
        fields = ['news_title', 'news_text', 'tags']
        labels = {'news_title':'Заголовок', 'news_text':'Текст статьи', 'tags':'Тэги'}

core/forms.py
import datetime


from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.forms import UserCreationForm
# Create your forms here.
from django.core.exceptions import ValidationError
from django.forms import ModelForm, DateInput

from UserSystem.models import CustomUser
from core.models import Project, Team, Skill, Direction



class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = CustomUser
        fields = ("username", "email", "password1", "password2")

    def clean_username(self):
        username = self.cleaned_data['username']

        if CustomUser.objects.filter(username=username).exists():
            raise forms.ValidationError("Это имя пользователя уже занято.")

        return username

    def clean_email(self):
        email = self.cleaned_data['email']

        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("Аккаунт с данной почтой уже существует.")

        return email

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class CreateProjectForm(ModelForm):
    #project_start = forms.DateTimeField()
    #datetime forms compatible with xdsoft timepicker and Europe time formats:
    project_start = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=forms.DateInput(format='%d.%m.%Y %H:%i'), label="Начало проекта")
    project_end = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'],
                                        widget=forms.DateInput(format='%d.%m.%Y %H:%i'), label="Конец проекта")
    class Meta:
        model = Project
        fields = ['project_name', 'project_info', 'event_type', 'direction_type', 'project_skills', 'project_start',
                  'project_end', ]
        labels = {'project_name': 'Название проекта', 'project_info': 'Информация о проекте',
                  'event_type': 'Тип проекта', 'direction_type': 'Название направления', 'project_skills': 'Навыки мероприятия',
                  'project_start': 'Начало проекта', 'project_end': 'Конец проекта'}

        widgets = {
            'project_info': forms.Textarea(attrs={'rows': 10, 'cols': 40}),
        }

    def __init__(self, *args, **kwargs):
        super(CreateProjectForm, self).__init__(*args, **kwargs)
        self.fields['direction_type'].queryset = Direction.objects.all()
        self.fields['project_skills'].queryset = Skill.objects.none()  # Initially empty

    def save(self, commit=True):
        instance = super(CreateProjectForm, self).save(commit=commit)
        # Обновляем queryset skills после сохранения объекта, чтобы применить фильтр
        self.fields['project_skills'].queryset = Skill.objects.filter(direction=instance.direction_type)
        return instance

    def clean_direction_type(self):
        direction = self.cleaned_data.get('direction_type')
        if direction:
            self.fields['project_skills'].queryset = Skill.objects.filter(direction=direction)
        return direction

    def clean_project_end(self):
        data = self.cleaned_data['project_end']
        if data.date() < datetime.date.today():
            raise ValidationError('Время конца не может быть в прошлом')
        if self.cleaned_data['project_start'].date() >= self.cleaned_data['project_end'].date():
            if self.cleaned_data['project_start'].date() == self.cleaned_data['project_end'].date() and (self.cleaned_data['project_start'].time()) >= self.cleaned_data['project_end'].time():
                raise ValidationError('Время конца проекта должно быть хотя бы на минуту позже начала')
            else: #if the same date, but starts earlier than ends
                return data
            raise ValidationError('Проект не может заканчиваться раньше, чем начнется')
        return data

    def clean_project_start(self):
        data = self.cleaned_data['project_start']
        if data.date() < datetime.date.today():
            raise ValidationError('Время начала не может быть в прошлом')
        return data


class CreateTeamForm(ModelForm):
    class Meta:
        model = Team
        fields = ['team_name', 'team_info', 'team_lfg_message', 'is_looking_for_group']
        labels = {'team_name':'Название команды', 'team_info':'Информация о команде', 'is_looking_for_group':'Открывать ли команду для поиска участников', 'team_lfg_message':'Сообщение в канал поиска участников'}

NewsFeed/templates/NewsFeed/article_form.html
{% extends "base.html" %}
{% block header %}
<head>
 {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'NewsFeed/style.css' %}">

    <!-- Use this block to integrate XDSOFT timepicker -->
    <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

    <!-- end of a block -->
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}"/>
    <style>
        table{
            width: 80%;
        }

    </style>
    {{ forms.media }}
    {{ form.media }}
</head>
{% endblock %}
{% block title %}
<title>Проект</title>
{% endblock %}
{% block content %}
    <form action="" method="post" align="center" autocomplete="off">
    {% csrf_token %}
    <table align="center" id="add_article_form">
    {{ form }}
    </table>
    <input type="submit" value="Submit" />
    </form>
    <!-- Use this block to bind XDSOFT timepicker to datetime widgets -->
    <script>
    $(function () {
        jQuery.datetimepicker.setLocale('ru');
      $("#id_project_start").datetimepicker({format:'d/m/Y H:i'});
      $("#id_project_end").datetimepicker({format:'d/m/Y H:i'});
    });
    </script>
    <!-- end of a block -->
{% endblock %}

NewsFeed/templates/NewsFeed/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>Новости</title>
{% endblock %}
{% block content %}
    {{ form.media }}
<article>
    <h1>{{ newsarticle.news_title }}</h1>
    <div>{{ newsarticle.formatted_markdown|safe}}</div>
    <div class="tag_container">
    {% for tag in newsarticle.tags.all %}
            <p class="tag" style="display:inline;"><a href="{% url 'NewsFeed:news_tag_filtered' tag.tag_name %}">#{{ tag.tag_name }}</a></p>
        {% endfor %}
    </div>
    <p>Опубликовано: {{ newsarticle.pub_date }}</p>
    <div class="commentBlock">
        Комментарии:
        {% for comment in newsarticle.comment_set.all %}
            <div class="box">
						<div class="Name">{{comment.user_id.username}} {{comment.pub_time}}
                        <p>{{comment.comment_text}}</p>
                        </div>
			</div>
        {% endfor %}
    {% if user.is_authenticated %}
        <div id="messagewindow">
				<form name = "f2" action="{% url 'NewsFeed:send_comment' newsarticle.pk  %}" method="post">
				{% csrf_token %}
                    <div id="sendcontainer"><textarea  name="comment_text" cols="40" rows="5" placeholder="Write your comment here..." id="chatbox"> </textarea>
					<div id="buttoncontainer">
						<input type="submit" name="button" value="Отправить" id="sendbutton">
					</div>
                    <textarea style="display: none;" name="user_id">1</textarea>
				</div>
				</form>
        </div>
    {% else %}
        <p align="center" class="login_to_comment_warning">Войдите, чтобы оставить комментарий</p>
    {% endif %}

    </div>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
</article>
{% endblock %}

NewsFeed/templates/NewsFeed/index-reworked.html
{% extends "base.html" %}
{% block title %}
<title>Новости</title>
{% endblock %}
{% block content %}
    {% if tag %}
        <p align="center"><a href="{% url 'NewsFeed:news' %}">Сбросить фильтры</a></p>
    {% endif %}
{% if latest_article_list %}
    {% for news_article in latest_article_list %}
        <article><h2><a href="{% url 'NewsFeed:detail' news_article.id %}">{{ news_article.news_title }}</a></h2>
        <div class="flex-body" style="display: flex; justify-content: space-between">
            <div class="articleMainBody">{{news_article.formatted_markdown|safe}}  </div>
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Telegram_logo.svg/2048px-Telegram_logo.svg.png" style="height: 256px; width: 256px; padding-left: 50px;">
        </div>
        <div class="commentsCounter">
            Комментарии: {{ news_article.comment_set.count }}
        </div>
        {% for tag in news_article.tags.all %}
            <p class="tag" style="display:inline;"><a href="{% url 'NewsFeed:news_tag_filtered' tag.tag_name %}">#{{ tag.tag_name }}</a></p>
        {% endfor %}
        </article>
    {% endfor %}
    <div class="page_navigator">
        <div class="page_wrap">
            {% for page_num in page_numbers %}
            <div class="page_ref" > <a href="{% url 'NewsFeed:news_on_page' page_num %}" {% if current_page == page_num %} id="current_page_num" {% endif %}>{{ page_num }}</a></div>
            {% endfor %}
        </div>
    </div>
{% else %}
    <div class="empty_page_warning">
        <p style="font-family: Calibri; font-size: 4vw;">WELCOME TO THE VOID</p>
        <p style="text-align: center; font-size: 20px">Seems like nothing is here yet.</p>
        <p style="text-align: center;"><a style="margin: 0 auto; color:white; font-size: 20px;" href="{% url 'NewsFeed:news_on_page' 1 %}">Return to the main page?</a></p>
    </div>
{% endif %}

{% endblock %}

NewsFeed/templates/NewsFeed/index.html
{% extends "base.html" %}
{% block title %}
<title>Новости</title>
{% endblock %}
{% block content %}
    {% if tag %}
        <p align="center"><a href="{% url 'NewsFeed:news' %}">Сбросить фильтры</a></p>
    {% endif %}
    {% if perms.NewsFeed.can_add_news_article %}
        <div class="shadebox centered-container"><a href="{% url 'NewsFeed:create_article' %}"> Добавить новость </a></div>
    {% endif %}
{% if latest_article_list %}
    {% for news_article in latest_article_list %}
        <article><h2><a href="{% url 'NewsFeed:detail' news_article.id %}">{{ news_article.news_title }}</a></h2>
        <div class="flex-body" style="display: flex; justify-content: space-between">
            <div class="articleMainBody">{{news_article.formatted_markdown|safe}}  </div>
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Telegram_logo.svg/2048px-Telegram_logo.svg.png" style="height: 256px; width: 256px; padding-left: 50px;">
        </div>
        <div class="commentsCounter">
            Комментарии: {{ news_article.comment_set.count }}
        </div>
        {% for tag in news_article.tags.all %}
            <p class="tag" style="display:inline;"><a href="{% url 'NewsFeed:news_tag_filtered' tag.tag_name %}">#{{ tag.tag_name }}</a></p>
        {% endfor %}
        </article>
    {% endfor %}
    <div class="page_navigator">
        <div class="page_wrap">
            {% for page_num in page_numbers %}
            <div class="page_ref" > <a href="{% url 'NewsFeed:news_on_page' page_num %}" {% if current_page == page_num %} id="current_page_num" {% endif %}>{{ page_num }}</a></div>
            {% endfor %}
        </div>
    </div>
{% else %}
    <div class="empty_page_warning">
        <p style="font-family: Calibri; font-size: 4vw;">WELCOME TO THE VOID</p>
        <p style="text-align: center; font-size: 20px">Seems like nothing is here yet.</p>
        <p style="text-align: center;"><a style="margin: 0 auto; color:white; font-size: 20px;" href="{% url 'NewsFeed:news_on_page' 1 %}">Return to the main page?</a></p>
    </div>
{% endif %}

{% endblock %}